#!/bin/bash
#fourth session for the shell scripting practise
#lets see how good i can make it


while true
do
echo
echo "=========== Welcome to the information center ======="
echo
echo "Please select one of the followings to proceed."
echo
echo "a)Basics information"
echo "b)Intermdediate information"
echo "c)Advanced information"
echo "d)Exit"
echo

read choice
case $choice in

a)
	echo "Please select one of the following"
	echo "1=Hostname"
	echo "2=Date & Time"
	echo "3=Working directory"
	
	read option
case $option in
	1)hostname;;
	2)date;;
	3)pwd;;
	*)echo "Please try again from the available options"
		
esac
;;

b)
	echo "Please select one of the following"
	echo "1=Ip address"
	echo "2=Check connection to internet"
	echo "3=Check disk usage"
	read op
	case $op in
		1)ip addr show;;
		2)ping -c 2 google.com;;
		3)df -h;;
		*)echo "Please try again from the available options" ;;
	
	esac

	;;

c) 	echo "Please select one of the following"
	echo "1=Active sockets per page"
	echo "2=Trace an ip route"
	echo "3=Check git status"

	read adv
	case $adv in
		1)ss | more ;;
		2)traceroute;;
		3)git status;;
		*)echo "Please try again from the available options" 
	esac ;;

*)echo "Please try again from the available options" 

esac 	
done
